APPLICATION_NAME = "SpatialCache"
VERSION = "0.1"
CONFIGURATION_FILE = "/etc/wmscache/configuration.xml"
HELP_FILE = "help"
DEFAULT_TILES_PATH = "/tmp/wmscache"
DEFAULT_WMS = "http://localhost:8080/wms"
